### ISSUE TITLE
a few lines in the result file .rawcnv

### ISSUE THREAD

**Issue by xgdong** [WGLab/PennCNV#20]
Dear Dr. Wang
  I'm using PennCNV to perform CNV calling from Affymetrix 600K Axiom Chicken Genotyping Array, the commond is as below: perl detect_cnv.pl -test -hmm affygw6.hmm -pfb ly.pfb -list filelist.txt -lastchr 28 -log ly.log -out ly.rawcnv ,it runs successfully, however, I'm a little confused that only ~70 lines generated in the result file ly.rawcnv, it means only 70 CNVs detected which is quite less than other reports. I'm not sure about the result, do you have any suggestions for the result? And another problem if I want to use GCModel how can I get GCModel file? 
Many thanks!
  Dong

**Comment by kaichop** [comment]
The number of CNVs depends on the array, and depends on the thresholds of
calling. I am not familiar with your specific array but for a 600K array,
70 CNV is a quite reasonable number.

**Comment by Rachael-rq** [comment]
Hi Dr. Wang,

The data I'm analysing were obtained using InfiniumCoreExome-24v1-1 beadchip. I have only got 20 or so CNVs with PennCNV which seems to be much less than expected. I've also run cnvPartition3.2 which returned about 25 CNVs for each sample. Do you think it may be due to the low density array? 

And I'm using a PFB file downloaded from PennCNV website, in the log file there is 
"Reading LRR and BAF values for from ...\PennCNV\PennCNV-1.0.4\rawdata\200581260003\sample.1000628 ... Done with 521399 records in 26 chromosomes (30440 records are discarded due to lack of PFB information for the markers)"

Could this also reduce the number of CNVs detected ?


Thank you

Best regards,
Ruqian

**Comment by kaichop** [comment]
I am not familiar with this array, but for an array with only 500K markers,
it is very reasonable to have ~20 CNVs per sample.

The 30K records should not affect the calling much and this is not the
reason.

**Comment by Rachael-rq** [comment]
Okay, I see, thank you for answering my question :)


Cheers,
Ruqian

2018-01-05 14:58 GMT+11:00 Kai Wang <notifications@github.com>:
