### ISSUE TITLE
Segmentation fault-detect_cnv.pl

### ISSUE THREAD

**Issue by moshl** [WGLab/PennCNV#34]
hi, I want to call CNV for affymetrix SNP6.0 by PennyCNV, but I run the final step-detect_cnv.pl, i meet the problem as below.
the code: ./detect_cnv.pl -test -hmm ./gw6/lib/affygw6.hmm -pfb ./gw6/lib/affygw6.hg19.pfb  NR.B01_181507A_NR1_R1 -log NR.log -out NR.rawcn

the log: "NOTICE: All program notification/warning messages that appear in STDERR will be also written to log file NR.log
NOTICE: Reading marker coordinates and population frequency of B allele (PFB) from /pnas/liuxin_group/moshl/software/gw6/lib/affygw6.hg19.pfb ... Done with 1878054 records
NOTICE: Reading LRR and BAF values for from NR.B01_181507A_NR1_R1 ... Done with 1847835 records in 24 chromosomes
NOTICE: Data from chromosome X,Y will not be used in analysis
NOTICE: Median-adjusting LRR values for all autosome markers from NR.B01_181507A_NR1_R1 by -0.0606
NOTICE: Median-adjusting BAF values for all autosome markers from NR.B01_181507A_NR1_R1 by 0.0008
NOTICE: quality summary for NR.B01_181507A_NR1_R1: LRR_mean=0.0174 LRR_median=0.0000 LRR_SD=0.4211 BAF_mean=0.4993 BAF_median=0.5000 BAF_SD=0.0870 BAF_DRIFT=0.009043 WF=-0.0390 GCWF=-0.0141
WARNING: Sample from NR.B01_181507A_NR1_R1 does not pass default quality control criteria due to its large SD for LRR (0.421119804166937)!
WARNING: Sample from NR.B01_181507A_NR1_R1 does not pass default quality control criteria due to its drifting BAF values (drift=0.00904313006810173)!
WARNING: Small-sized CNV calls may not be reliable and should be interpreted with caution!
Segmentation fault "
I try to the problem by advise from "detect_cnv.pl resulting in "Segmentation fault: 11" #7", but the problem still be existed. Looking forward to your reply. 
p.s version of my perl is v5.16.3.

bestwishes.
mo

**Comment by kaichop** [comment]
It is difficult to tell what is wrong from the information above. I would advise that (1) make sure you recompile the source code using "make clean" and "make" (2) check memory usage; sometimes it is just a simple memory issue. You can even just analyze a small proportion of the file and see whether there is segmentation fault; if not, then it may be an out-of-memory issue (3) otherwise, update to the latest PennCNV that is just updated, and then install a new perl such as 5.14.2 as instructed in the "installation" section, and then recompile again.
